all: 
	echo "Please specify a target!\nex01, ex02, ex03, ex07 clean"

ex01: ex1/Heap.cpp ex1/main.cpp ex1/StringContainer.cpp
	g++ -Wall -g -o ex1/$@ ex1/Heap.cpp ex1/main.cpp ex1/StringContainer.cpp

test: aufgabe1
	./aufgabe1

clean: 
	rm -f aufgabe1
