all: 
	@echo "Please specify a target!\nex01, ex02, ex03, ex07 clean"

ex01: ex1/main.cpp
	g++ -Wall -g -o ex1/$@ ex1/main.cpp

ex02: ex2/main.cpp
	g++ -Wall -g -o ex2/$@ ex2/main.cpp

ex03: ex3/main.cpp
	g++ -Wall -g -o ex3/$@ ex3/main.cpp

test: aufgabe1
	./aufgabe1

clean: 
	rm -f aufgabe1
